language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.4"
      install: pip install tox-travis poetry~=1.0.a
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial
  allow_failures:
    - python: "3.8-dev"
install: pip install tox-travis poetry
script: tox
env:
  - POST_COMMAND="codecov -e TOX_ENV"
